- name: Roboshop Project - Frontend
  hosts: all
  become: true
  tasks:
    - name: Copy Roboshop configuration
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: Replace Listening address in mongodb config
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start Mongodb
      ansible.builtin.systemd:
        state: restarted
        name: mongod
        enabled: yes


#  echo -e "\e[34m>>>>>>>>>>> Install MongoDB Repo <<<<<<<<<<<<\e[0m"
# cp Mongo.service /etc/yum.repos.d/mongo.repo &>>/tmp/roboshop.log

#echo -e "\e[34m>>>>>>>>>>> Install MongoDB <<<<<<<<<<<<\e[0m"
#yum install mongodb-org -y &>>/tmp/roboshop.log
  
#echo -e "\e[34m>>>>>>>>>>> Replace mongo.conf <<<<<<<<<<<<\e[0m"
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>/tmp/roboshop.log

#echo -e "\e[34m>>>>>>>>>>> Start MongoDB <<<<<<<<<<<<\e[0m"
#systemctl enable mongod &>>/tmp/roboshop.log
#systemctl restart mongod &>>/tmp/roboshop.logz