- name: MySQL setup
  hosts: all
  become: true
  tasks:
    - name: configure MySQL repo yum
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Disable existing MySQL version
      ansible.builtin.shell: yum module disable mysql -y

    - name: Install MySQL community server
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: Start MySQL service
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes

    - name: Set Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

#    - name: Set user application
#      ansible.builtin.shell: mysql -uroot -pRoboShop@1









