- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Nodejs repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Install Nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Load Schema
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: SystemD setup
  ansible.builtin.import_tasks: systemd-setup.yml



#curl -sL https://rpm.nodesource.com/setup_lts.x | bash

#yum install nodejs -y

#useradd roboshop
#mkdir /app

#curl -L -o /tmp/cart.zip https://roboshop-artifacts.s3.amazonaws.com/cart.zip
#cd /app
#unzip /tmp/cart.zip

#cd /app
#npm install

#cp Cart.service /etc/systemd/system/cart.service

#systemclt daemon-reload
#systemclt enable cart
#systemclt restart cart

