- name: User
  hosts: all
  become: true
  vars:
    component: user
    schema: true
  tasks:
    - name: NodeJs Setup
      ansible.builtin.import_tasks: nodejs.yml



#component=user
#schema_type=mongodb
#source common.sh
#
#nodejs